### ISSUE TITLE
A2.10.d Sprint retrospective carried out, analysis of each Sprint, and action plan to improve team work for Sprint 3

### ISSUE THREAD

**Issue by carlos-bermejo** [gii-is-psg2/PSG2-2223-G6-62#19]
Retrospectiva de Sprint realizada, análisis de cada Sprint y plan de acción para mejorar el trabajo en equipo para el Sprint 3.

**Comment by manbarjim2** [comment]
Completed correctly, the application is well deployed.

**Comment by marizqlav** [comment]
The meeting and the diagram used in said meeting are well documented
