### ISSUE TITLE
A2.6 Create a technical report that describes the history of the project.

### ISSUE THREAD

**Issue by raumonmar1** [gii-is-psg2/PSG2-2223-G6-62#5]
En grupo, elaboren un informe técnico (en español) que describa la historia del proyecto después de terminar con las tareas anteriores. Este documento debe incluir un diagrama que muestre una línea de tiempo de los compromisos con el repositorio, identificando los conflictos que surgieron, si los hubo, y describiendo cómo el grupo resolvió esos conflictos. El documento debe almacenarse en una carpeta docs dentro del mismo repositorio, actualizando las versiones almacenadas a medida que el grupo trabaja con él.

**Comment by carlos-bermejo** [comment]
It's completed.
